### ISSUE TITLE
Cannot download through gradle

### ISSUE THREAD

**Issue by kccheung** [SeanZoR/shared-preferences-helper#1]
I added 

`compile 'com.github.seanzor:shared-preferences-helper:1.0.1'`

to my gradle but receive the following error:

Error:Could not find com.github.seanzor:shared-preferences-helper:1.0.1.
Required by:
    your_app:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by SeanZoR** [comment]
Hi, the readme was incorrect. got it fixed now (5c44b7e34a1081f0895bb58a1e3f927248c2677f).

Please use:
`compile 'com.github.seanzor:shared-preferences-helper:1.1.0'`
